name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build IPA for iOS
    runs-on: macos-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment for React Native
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm install

      # Step 4: Install CocoaPods for iOS dependencies
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios && pod install --repo-update

      # Step 5: List available Xcode schemes (for debugging purposes)
      - name: List Xcode schemes
        run: xcodebuild -workspace ios/HelloWorld.xcworkspace -list

      # Step 6: Build the iOS app
      - name: Build the app
        run: xcodebuild -workspace ios/HelloWorld.xcworkspace \
                        -scheme HelloWorld \
                        -sdk iphoneos \
                        -configuration Release \
                        archive -archivePath $PWD/build/MyApp.xcarchive

      # Step 7: Export the IPA file
      - name: Export IPA
        run: xcodebuild -exportArchive \
                        -archivePath $PWD/build/MyApp.xcarchive \
                        -exportOptionsPlist ios/exportOptions.plist \
                        -exportPath $PWD/build

      # Step 8: Upload the IPA as an artifact for download
      - name: Upload IPA as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-IPA
          path: build/MyApp.ipa
