name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build IPA for iOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios && pod install --repo-update

      - name: Build the app
        run: xcodebuild -workspace ios/MyApp.xcworkspace \
                        -scheme MyApp \
                        -sdk iphoneos \
                        -configuration Release \
                        archive -archivePath $PWD/build/MyApp.xcarchive

      - name: Export IPA
        run: xcodebuild -exportArchive \
                        -archivePath $PWD/build/MyApp.xcarchive \
                        -exportOptionsPlist ios/exportOptions.plist \
                        -exportPath $PWD/build

      - name: Upload IPA as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-IPA
          path: build/MyApp.ipa
