name: iOS Build

on:
  push:
    branches:
      - main # Trigger the build on pushes to the main branch

jobs:
  build-ios:
    runs-on: macos-latest # Use GitHub's macOS environment to build for iOS

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Match the Node.js version to your project requirements

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          npm install
          cd ios && pod install && cd ..

      # Step 4: Set up Ruby for Fastlane
      - name: Set up Ruby for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # Ensure compatibility with Fastlane and macOS versions

      # Step 5: Install Fastlane
      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      # Step 6: Build the iOS app using Fastlane
      - name: Build iOS App
        run: |
          bundle exec fastlane build
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # Secret for signing
          GITHUB_WORKFLOW: ${{ github.workflow }}

      # Step 7: Upload Build Artifacts (optional)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: ios/build
